openapi: 3.0.0
info:
  title: いいね
  version: '1.0'
servers:
  - url: 'https://d32rxh06xfiiaj.cloudfront.net/api/v1'
    description: 開発版
paths:
  /like/:
    get:
      summary: いいね一覧
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                  offset:
                    type: number
                  data:
                    type: array
                    items:
                      $ref: './出品処理.v1.yaml#/components/schemas/Exhibit'
      operationId: get-like
  '/like/{exhibitCode}/':
    parameters:
      - schema:
          type: string
        name: exhibitCode
        in: path
        required: true
    put:
      summary: いいね実行
      operationId: put-like-exhibitCode
      responses:
        '200':
          description: OK
    delete:
      summary: いいねキャンセル
      operationId: delete-like-exhibitCode
      responses:
        '200':
          description: OK
components:
  schemas: {}
