openapi: 3.0.0
info:
  title: ユーザー関連
  version: '1.0'
servers:
  - url: 'https://d32rxh06xfiiaj.cloudfront.net/api/v1'
    description: 開発版
paths:
  /login/:
    post:
      summary: ログイン実行
      operationId: post-login
      responses:
        '200':
          description: OK
  '/user/{$id}/':
    parameters:
      - schema:
          type: string
        name: $id
        in: path
        required: true
    get:
      summary: 他人ユーザー取得
      tags: []
      responses: {}
      operationId: get-user-$id
  /coupon/:
    get:
      summary: 所有クーポン一覧
      tags: []
      responses: {}
      operationId: get-coupon
components:
  schemas: {}
