openapi: 3.0.0
info:
  title: 交渉処理
  version: '1.0'
servers:
  - url: 'https://d32rxh06xfiiaj.cloudfront.net/api/v1'
    description: 開発版
paths:
  /offer/price/:
    post:
      summary: 価格相談申込
      operationId: post-offer-price
      responses:
        '200':
          description: OK
  /offer/:
    post:
      summary: 購入依頼
      operationId: post-offer
      responses:
        '200':
          description: OK
  /offer/ok/:
    post:
      summary: 売却承諾
      operationId: post-offer-ok
      responses:
        '200':
          description: OK
  /offer/ng/:
    get:
      summary: 売却拒否
      tags: []
      responses: {}
      operationId: get-offer-ng
components:
  schemas: {}
