openapi: 3.0.0
info:
  title: 取引処理
  version: '1.0'
servers:
  - url: 'https://d32rxh06xfiiaj.cloudfront.net/api/v1'
    description: 開発版
paths:
  '/transact/receive/{transactCode}/':
    parameters:
      - schema:
          type: string
        name: transactCode
        in: path
        required: true
    put:
      summary: 受取方法変更
      operationId: put-transact-receive-$transactCode
      responses:
        '200':
          description: OK
  '/transact/card/{transactCode}/':
    parameters:
      - schema:
          type: string
        name: transactCode
        in: path
        required: true
    put:
      summary: カード決済要求
      operationId: put-transact-card-transactCode
      responses:
        '200':
          description: OK
  '/transact/bank/{transactCode}/':
    parameters:
      - schema:
          type: string
        name: transactCode
        in: path
        required: true
    put:
      summary: 銀行振込要求
      operationId: put-transact-bank-transactCode
      responses:
        '200':
          description: OK
  '/transact/document/{transactCode}/':
    parameters:
      - schema:
          type: string
        name: transactCode
        in: path
        required: true
    post:
      summary: 書類アップロード
      operationId: post-transact-document-transactCode
      responses:
        '200':
          description: OK
    put:
      summary: 書類受取完了報告
      operationId: put-transact-document-transactCode
      responses:
        '200':
          description: OK
  '/transact/complete/{transactCode}/':
    parameters:
      - schema:
          type: string
        name: transactCode
        in: path
        required: true
    put:
      summary: 車両受取完了報告
      operationId: put-transact-complete-transactCode
      responses:
        '200':
          description: OK
    post:
      summary: 車両発送通知
      operationId: post-transact-complete-transactCode
      responses:
        '200':
          description: OK
  /transact/delivery/:
    post:
      summary: ''
      operationId: post-transact-delivery
      responses:
        '200':
          description: OK
  '/message/{transactCode}/':
    parameters:
      - schema:
          type: string
        name: transactCode
        in: path
        required: true
    get:
      summary: 取引メッセージ一覧
      tags: []
      responses: {}
      operationId: get-message-transactCode
    post:
      summary: 取引メッセージ作成
      operationId: post-message-transactCode
      responses:
        '200':
          description: OK
components:
  schemas: {}
