openapi: 3.0.0
info:
  title: 検索条件保存
  version: '1.0'
servers:
  - url: 'https://d32rxh06xfiiaj.cloudfront.net/api/v1'
    description: 開発版
paths:
  /search/:
    get:
      summary: 検索条件一覧
      tags: []
      responses: {}
      operationId: get-search
      description: 検索条件一覧
      parameters: []
  '/search/{searchCode}/':
    parameters:
      - schema:
          type: string
        name: searchCode
        in: path
        required: true
    put:
      summary: 検索条件変更
      operationId: put-search-searchCode
      responses:
        '200':
          description: OK
    delete:
      summary: 検索条件削除
      operationId: delete-search-searchCode
      responses:
        '200':
          description: OK
components:
  schemas:
    Search:
      title: 検索条件構造体
      type: object
      properties:
        searchCode:
          type: number
        searchName:
          type: string
        searchQuery:
          type: string
  securitySchemes: {}
